# Generated by Django 4.1.5 on 2023-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_pic',
            field=models.ImageField(blank=True, default='defaultProdPic.png', null=True, upload_to='prod_images'),
        ),
    ]
