# Generated by Django 4.1.5 on 2023-02-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_date',
        ),
    ]
