# Generated by Django 4.1.5 on 2023-02-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_product_buy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bought_by',
        ),
    ]
