# Generated by Django 4.1.5 on 2023-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_remove_transactionseller_bought_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='prod_pic',
            field=models.TextField(blank=True, default='defaultProdPic.png', null=True),
        ),
    ]
