# Generated by Django 4.1.5 on 2023-02-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_wishlist'),
        ('cart', '0002_remove_cart_cart_owner_cart_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_added', to='market.product'),
        ),
    ]
